In [1]:
import numpy as np


In [2]:
import array


In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
type(np.array([1,2,3,4,5]))#nd array states that n dimentional array
# it converts the list into nd array

numpy.ndarray

In [10]:
np.array([[1,2],[1,6,87]])

C:\Users\Sameer\AppData\Local\Temp\ipykernel_6496\3615323588.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2],[1,6,87]])


array([list([1, 2]), list([1, 6, 87])], dtype=object)

In [13]:
np.array([2,3], ndmin = 4) #ndmin states the dinemtions for the array

array([[[[2, 3]]]])

In [14]:
np.mat([[2,3],[4,5]]) #defining matrix 


matrix([[2, 3],
        [4, 5]])

In [16]:
np.fromfunction(lambda i,j :i==j,(5,5))    #from function defines array depending on login given in the function

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [17]:
np.fromfunction(lambda i,j : i*j ,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [20]:
(i*i for i in range(9)) #range function is also a generator function

<generator object <genexpr> at 0x000001F8D98ED7E0>

In [23]:
#extracting array from strings
np.fromstring("artificial intelligence and machine learning" ,sep = " ", dtype=str)

ValueError: zero-valued itemsize