In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [108]:
df_train = pd.read_csv('Datasets/train.csv')

In [109]:
df_train['Exited'].unique()

array([0, 1], dtype=int64)

In [110]:
df_test = pd.read_csv('Datasets/test.csv')

In [111]:
df = df_train.append(df_test)

C:\Users\Sameer\AppData\Local\Temp\ipykernel_8872\925505788.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df_train.append(df_test)


In [112]:
df['Exited'].unique()

array([ 0.,  1., nan])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 275057 entries, 0 to 110022
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   id               275057 non-null  int64  
 1   CustomerId       275057 non-null  int64  
 2   Surname          275057 non-null  object 
 3   CreditScore      275057 non-null  int64  
 4   Geography        275057 non-null  object 
 5   Gender           275057 non-null  object 
 6   Age              275057 non-null  float64
 7   Tenure           275057 non-null  int64  
 8   Balance          275057 non-null  float64
 9   NumOfProducts    275057 non-null  int64  
 10  HasCrCard        275057 non-null  float64
 11  IsActiveMember   275057 non-null  float64
 12  EstimatedSalary  275057 non-null  float64
 13  Exited           165034 non-null  float64
dtypes: float64(6), int64(5), object(3)
memory usage: 31.5+ MB


In [9]:
df.columns

Index(['id', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender',
       'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [12]:
df.drop(columns = ['id', 'CustomerId', 'Surname'],inplace  = True)

In [13]:
df

CreditScore Geography  Gender   Age  Tenure    Balance  NumOfProducts  \
0               668    France    Male  33.0       3       0.00              2   
1               627    France    Male  33.0       1       0.00              2   
2               678    France    Male  40.0      10       0.00              2   
3               581    France    Male  34.0       2  148882.54              1   
4               716     Spain    Male  33.0       5       0.00              2   
...             ...       ...     ...   ...     ...        ...            ...   
110018          570     Spain    Male  29.0       7  116099.82              1   
110019          575    France  Female  36.0       4  178032.53              1   
110020          712    France    Male  31.0       2       0.00              2   
110021          709    France  Female  32.0       3       0.00              1   
110022          621    France  Female  37.0       7   87848.39              1   

        HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1.0             0.0        181449.97     0.0  
1             1.0             1.0         49503.50     0.0  
2             1.0             0.0        184866.69     0.0  
3             1.0             1.0         84560.88     0.0  
4             1.0             1.0         15068.83     0.0  
...           ...             ...              ...     ...  
110018        1.0             1.0        148087.62     NaN  
110019        1.0             1.0         42181.68     NaN  
110020        1.0             0.0         16287.38     NaN  
110021        1.0             1.0        158816.58     NaN  
110022        1.0             0.0         24210.56     NaN  

[275057 rows x 11 columns]

In [15]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

In [16]:
# df['species']= label_encoder.fit_transform(df['species']) 
def label_enc(df,cols):
    for column in cols:
        df[column] = label.fit_transform(df[column])

In [17]:
label_enc(df,['Geography', 'Gender'])

In [19]:
df

CreditScore  Geography  Gender   Age  Tenure    Balance  \
0               668          0       1  33.0       3       0.00   
1               627          0       1  33.0       1       0.00   
2               678          0       1  40.0      10       0.00   
3               581          0       1  34.0       2  148882.54   
4               716          2       1  33.0       5       0.00   
...             ...        ...     ...   ...     ...        ...   
110018          570          2       1  29.0       7  116099.82   
110019          575          0       0  36.0       4  178032.53   
110020          712          0       1  31.0       2       0.00   
110021          709          0       0  32.0       3       0.00   
110022          621          0       0  37.0       7   87848.39   

        NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0                   2        1.0             0.0        181449.97     0.0  
1                   2        1.0             1.0         49503.50     0.0  
2                   2        1.0             0.0        184866.69     0.0  
3                   1        1.0             1.0         84560.88     0.0  
4                   2        1.0             1.0         15068.83     0.0  
...               ...        ...             ...              ...     ...  
110018              1        1.0             1.0        148087.62     NaN  
110019              1        1.0             1.0         42181.68     NaN  
110020              2        1.0             0.0         16287.38     NaN  
110021              1        1.0             1.0        158816.58     NaN  
110022              1        1.0             0.0         24210.56     NaN  

[275057 rows x 11 columns]

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 275057 entries, 0 to 110022
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   CreditScore      275057 non-null  int64  
 1   Geography        275057 non-null  int32  
 2   Gender           275057 non-null  int32  
 3   Age              275057 non-null  int32  
 4   Tenure           275057 non-null  int64  
 5   Balance          275057 non-null  float64
 6   NumOfProducts    275057 non-null  int64  
 7   HasCrCard        275057 non-null  float64
 8   IsActiveMember   275057 non-null  float64
 9   EstimatedSalary  275057 non-null  float64
 10  Exited           165034 non-null  object 
dtypes: float64(4), int32(3), int64(3), object(1)
memory usage: 22.0+ MB


In [22]:
df['Age'] = df['Age'].astype(int)

In [24]:
df.Exited.unique()

array([ 0.,  1., nan])

In [28]:
df['Exited'] = df['Exited'].map({0. :False,  1.:True, 'nan':np.nan})

In [30]:
df.describe()

CreditScore      Geography         Gender            Age  \
count  275057.000000  275057.000000  275057.000000  275057.000000   
mean      656.484939       0.646401       0.563854      38.124400   
std        80.188100       0.815940       0.495907       8.864928   
min       350.000000       0.000000       0.000000      18.000000   
25%       597.000000       0.000000       0.000000      32.000000   
50%       659.000000       0.000000       1.000000      37.000000   
75%       710.000000       1.000000       1.000000      42.000000   
max       850.000000       2.000000       1.000000      92.000000   

              Tenure        Balance  NumOfProducts      HasCrCard  \
count  275057.000000  275057.000000  275057.000000  275057.000000   
mean        5.010867   55420.296450       1.554002       0.753589   
std         2.806173   62805.933171       0.546178       0.430921   
min         0.000000       0.000000       1.000000       0.000000   
25%         3.000000       0.000000       1.000000       1.000000   
50%         5.000000       0.000000       2.000000       1.000000   
75%         7.000000  120037.960000       2.000000       1.000000   
max        10.000000  250898.090000       4.000000       1.000000   

       IsActiveMember  EstimatedSalary  
count   275057.000000    275057.000000  
mean         0.496755    112470.952558  
std          0.499990     50286.608747  
min          0.000000        11.580000  
25%          0.000000     74580.800000  
50%          0.000000    117848.090000  
75%          1.000000    154871.130000  
max          1.000000    199992.480000

In [33]:
test = df[df['Exited'].isnull()]

In [36]:
train = df[df['Exited'].isnull() == False]

In [45]:
y = train['Exited'].astype(bool)

In [49]:
y.info()

<class 'pandas.core.series.Series'>
Int64Index: 165034 entries, 0 to 165033
Series name: Exited
Non-Null Count   Dtype
--------------   -----
165034 non-null  bool 
dtypes: bool(1)
memory usage: 1.4 MB


In [50]:
X = train.drop('Exited',axis = 1)

In [51]:
X

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0               668          0       1   33       3       0.00              2   
1               627          0       1   33       1       0.00              2   
2               678          0       1   40      10       0.00              2   
3               581          0       1   34       2  148882.54              1   
4               716          2       1   33       5       0.00              2   
...             ...        ...     ...  ...     ...        ...            ...   
165029          667          2       0   33       2       0.00              1   
165030          792          0       1   35       3       0.00              1   
165031          565          0       1   31       5       0.00              1   
165032          554          2       0   30       7  161533.00              1   
165033          850          0       1   31       1       0.00              1   

        HasCrCard  IsActiveMember  EstimatedSalary  
0             1.0             0.0        181449.97  
1             1.0             1.0         49503.50  
2             1.0             0.0        184866.69  
3             1.0             1.0         84560.88  
4             1.0             1.0         15068.83  
...           ...             ...              ...  
165029        1.0             1.0        131834.75  
165030        0.0             0.0        131834.45  
165031        1.0             1.0        127429.56  
165032        0.0             1.0         71173.03  
165033        1.0             0.0         61581.79  

[165034 rows x 10 columns]

In [53]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.4,random_state=1)

In [54]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)
log_reg_pred = log_reg.predict(X_test)

In [55]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [61]:
pred = log_reg_pred
print('Accurecy is ',accuracy_score(y_test,log_reg_pred))
print(confusion_matrix(y_test,log_reg_pred))
print(classification_report(y_test,log_reg_pred))

Accurecy is  0.7870148756324417
[[50317  1785]
 [12275  1637]]
              precision    recall  f1-score   support

       False       0.80      0.97      0.88     52102
        True       0.48      0.12      0.19     13912

    accuracy                           0.79     66014
   macro avg       0.64      0.54      0.53     66014
weighted avg       0.74      0.79      0.73     66014



In [60]:
from sklearn.svm import SVC 
svc = SVC()
svc.fit(X_train,y_train)
svc_pred = svc.predict(X_test)

In [62]:
pred = svc_pred
print('Accurecy is ',accuracy_score(y_test,log_reg_pred))
print(confusion_matrix(y_test,log_reg_pred))
print(classification_report(y_test,log_reg_pred))

Accurecy is  0.7870148756324417
[[50317  1785]
 [12275  1637]]
              precision    recall  f1-score   support

       False       0.80      0.97      0.88     52102
        True       0.48      0.12      0.19     13912

    accuracy                           0.79     66014
   macro avg       0.64      0.54      0.53     66014
weighted avg       0.74      0.79      0.73     66014



In [63]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf_pred = rf.predict(X_test)

In [64]:
pred = rf_pred
print('Accurecy is ',accuracy_score(y_test,log_reg_pred))
print(confusion_matrix(y_test,log_reg_pred))
print(classification_report(y_test,log_reg_pred))

Accurecy is  0.7870148756324417
[[50317  1785]
 [12275  1637]]
              precision    recall  f1-score   support

       False       0.80      0.97      0.88     52102
        True       0.48      0.12      0.19     13912

    accuracy                           0.79     66014
   macro avg       0.64      0.54      0.53     66014
weighted avg       0.74      0.79      0.73     66014



In [67]:
test.drop('Exited',axis = 1,inplace = True)


C:\Users\Sameer\AppData\Local\Temp\ipykernel_8872\2163756920.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test.drop('Exited',axis = 1,inplace = True)


In [68]:
pred = log_reg.predict(test)

In [81]:
sub =  pd.DataFrame(sub)

In [84]:
sub['Exited'] = pred

In [72]:
df_test

id  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0       165034    15773898   Lucchese          586    France  Female  23.0   
1       165035    15782418       Nott          683    France  Female  46.0   
2       165036    15807120         K?          656    France  Female  34.0   
3       165037    15808905  O'Donnell          681    France    Male  36.0   
4       165038    15607314    Higgins          752   Germany    Male  38.0   
...        ...         ...        ...          ...       ...     ...   ...   
110018  275052    15662091      P'eng          570     Spain    Male  29.0   
110019  275053    15774133        Cox          575    France  Female  36.0   
110020  275054    15728456      Ch'iu          712    France    Male  31.0   
110021  275055    15687541   Yegorova          709    France  Female  32.0   
110022  275056    15663942       Tuan          621    France  Female  37.0   

        Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0            2       0.00              2        0.0             1.0   
1            2       0.00              1        1.0             0.0   
2            7       0.00              2        1.0             0.0   
3            8       0.00              1        1.0             0.0   
4           10  121263.62              1        1.0             0.0   
...        ...        ...            ...        ...             ...   
110018       7  116099.82              1        1.0             1.0   
110019       4  178032.53              1        1.0             1.0   
110020       2       0.00              2        1.0             0.0   
110021       3       0.00              1        1.0             1.0   
110022       7   87848.39              1        1.0             0.0   

        EstimatedSalary  
0             160976.75  
1              72549.27  
2             138882.09  
3             113931.57  
4             139431.00  
...                 ...  
110018        148087.62  
110019         42181.68  
110020         16287.38  
110021        158816.58  
110022         24210.56  

[110023 rows x 13 columns]

In [89]:
sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110023 entries, 0 to 110022
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      110023 non-null  int64
 1   Exited  110023 non-null  bool 
dtypes: bool(1), int64(1)
memory usage: 967.1 KB


In [87]:
sub.to_csv('submission.csv')

In [90]:
sample = pd.read_csv('Datasets/sample_submission.csv')

In [91]:
sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110023 entries, 0 to 110022
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   id      110023 non-null  int64  
 1   Exited  110023 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 1.7 MB


In [92]:
sample

id  Exited
0       165034     0.5
1       165035     0.5
2       165036     0.5
3       165037     0.5
4       165038     0.5
...        ...     ...
110018  275052     0.5
110019  275053     0.5
110020  275054     0.5
110021  275055     0.5
110022  275056     0.5

[110023 rows x 2 columns]

In [93]:
sub.Exited.unique()

array([False,  True])

In [96]:
sub['Exited'] = sub['Exited'].map({False:0,  True:1})

In [120]:
sub['Exited'] =sub['Exited'].astype(float)

In [100]:
sub.to_csv('sub1.csv')

In [102]:
sample['Exited'].unique()

array([0.5])

In [107]:
df_train['Exited'].unique()

array([0, 1], dtype=int64)

In [106]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165034 entries, 0 to 165033
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   id               165034 non-null  int64  
 1   CustomerId       165034 non-null  int64  
 2   Surname          165034 non-null  object 
 3   CreditScore      165034 non-null  int64  
 4   Geography        165034 non-null  object 
 5   Gender           165034 non-null  object 
 6   Age              165034 non-null  float64
 7   Tenure           165034 non-null  int64  
 8   Balance          165034 non-null  float64
 9   NumOfProducts    165034 non-null  int64  
 10  HasCrCard        165034 non-null  float64
 11  IsActiveMember   165034 non-null  float64
 12  EstimatedSalary  165034 non-null  float64
 13  Exited           165034 non-null  int64  
dtypes: float64(5), int64(6), object(3)
memory usage: 17.6+ MB


In [121]:
sub.Exited.value_counts()

0.0    104152
1.0      5871
Name: Exited, dtype: int64

In [122]:
df_train.Exited.value_counts()

0    130113
1     34921
Name: Exited, dtype: int64