In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
df = pd.read_csv('Datasets/Arrithmia_cleaned.csv')

In [6]:
df.shape

(22634, 26)

In [15]:
df.drop(columns = ['Unnamed: 0', 'record'],inplace = True)

In [16]:
df.shape

(22634, 21)

In [10]:
def find_corr(dataset, threshold):
    cor_col = set()
    corr_matrix = df.corr(numeric_only = True)
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if(abs(corr_matrix.iloc[i,j])) > threshold:
                colname = corr_matrix.columns[i]
                cor_col.add(colname)
    return cor_col

In [11]:
find_corr(df,0.8)

set()

In [17]:
df.shape

(22634, 21)

In [18]:
X = df.drop('type',axis =1)

In [20]:
y = df['type']

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y , test_size=0.4,random_state=0)

## Accurecy listing 
1. SVC =  0.8195272807598851
2. Log_reg =  0.8061630218687873


In [22]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train,y_train)

SVC()

In [23]:
svc_pred = svc.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score, classification_report , confusion_matrix


In [25]:
pred = svc_pred
print("Accurecy is ", accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

Accurecy is  0.8195272807598851
              precision    recall  f1-score   support

           F       0.00      0.00      0.00       312
           N       0.80      0.96      0.87      4824
        SVEB       0.82      0.23      0.36      1124
         VEB       0.86      0.90      0.88      2794

    accuracy                           0.82      9054
   macro avg       0.62      0.52      0.53      9054
weighted avg       0.79      0.82      0.78      9054

[[   0  223    2   87]
 [   3 4648   33  140]
 [   1  680  257  186]
 [   3  254   22 2515]]


In [32]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(max_iter=10000000)
log_reg.fit(X_train,y_train)
log_reg_pred = log_reg.predict(X_test)

In [31]:
pred = log_reg_pred
print("Accurecy is ", accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

Accurecy is  0.8501214932626463
              precision    recall  f1-score   support

           F       0.76      0.42      0.54       312
           N       0.86      0.94      0.90      4824
        SVEB       0.69      0.50      0.58      1124
         VEB       0.89      0.88      0.89      2794

    accuracy                           0.85      9054
   macro avg       0.80      0.68      0.72      9054
weighted avg       0.84      0.85      0.84      9054

[[ 130  146    2   34]
 [  16 4552  147  109]
 [   5  408  558  153]
 [  20  214  103 2457]]
