In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
df = pd.read_csv('diabetes_dataset_cleaned.csv')

In [ ]:
X = df.drop(columns = ['Unnamed: 0','diabetes'])

In [ ]:
X

In [ ]:
y = df['diabetes']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.4,random_state=0)

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc =SVC()
svc.fit(X_train,y_train)

In [ ]:
svc_pred = svc.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


In [ ]:
predicted = svc_pred
print('Accurecy is ',accuracy_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dclf = DecisionTreeClassifier()
dclf.fit(X_train,y_train)
dclf_pred = dclf.predict(X_test)

In [ ]:
predicted = dclf_pred
print('Accurecy is ',accuracy_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb_clf= GaussianNB()
gnb_clf.fit(X_train,y_train)
gnb_pred = gnb_clf.predict(X_test)

In [ ]:
gnb_clf= GaussianNB()
gnb_clf.fit(X_train_scaled,y_train)
gnb_pred = gnb_clf.predict(X_test_scaled)
predicted = gnb_pred
print('Accurecy is ',accuracy_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

In [ ]:
predicted = gnb_pred
print('Accurecy is ',accuracy_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

In [ ]:
from sklearn.naive_bayes import BernoulliNB
b_clf= BernoulliNB()
b_clf.fit(X_train,y_train)
b_pred = gnb_clf.predict(X_test)

In [ ]:
b_clf.fit(X_train_scaled,y_train)
b_pred = gnb_clf.predict(X_test_scaled)
predicted = b_pred
print('Accurecy is ',accuracy_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

In [ ]:
predicted = b_pred
print('Accurecy is ',accuracy_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

In [ ]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train,y_train)
log_pred = log_reg.predict(X_test)

In [ ]:
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled,y_train)
log_pred = log_reg.predict(X_test_scaled)
predicted = log_pred
print('Accurecy is ',accuracy_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

In [ ]:
predicted = log_pred
print('Accurecy is ',accuracy_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [ ]:
# logreg, decision tree , svc
grid_values = {'penalty': ['l1','l2'], 'C': [0.001,0.01,0.1,1,10,100,1000]}
model_lr = GridSearchCV(LogisticRegression(), param_grid=grid_values)
model_lr.fit(X_train, y_train)   


In [ ]:
grig_log_reg = model_lr.predict(X_test)

In [ ]:
predicted = grig_log_reg
print('Accurecy is ',accuracy_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

In [ ]:
from sklearn.svm import SVC

In [ ]:
# params = {kernel{‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’} }
grid_values = {'kernel': ['linear','ploy','sigmoid','precomputed']}
model_lr = GridSearchCV(SVC(), param_grid=grid_values,verbose=4)
model_lr.fit(X_train, y_train)


In [12]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(X_train,y_train)

SVC(kernel='linear')

In [13]:
svc_pred = svc.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


In [16]:
predicted = svc_pred
print('Accurecy is ',accuracy_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

Accurecy is  0.959625
              precision    recall  f1-score   support

           0       0.96      0.99      0.98     36637
           1       0.88      0.60      0.71      3363

    accuracy                           0.96     40000
   macro avg       0.92      0.80      0.85     40000
weighted avg       0.96      0.96      0.96     40000

[[36370   267]
 [ 1348  2015]]


In [18]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(X_train_scaled,y_train)

SVC(kernel='linear')

In [20]:
predicted = svc_pred
print('Accurecy is ',accuracy_score(y_test,predicted))
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

Accurecy is  0.96065
              precision    recall  f1-score   support

           0       0.96      0.99      0.98     36637
           1       0.91      0.59      0.72      3363

    accuracy                           0.96     40000
   macro avg       0.93      0.79      0.85     40000
weighted avg       0.96      0.96      0.96     40000

[[36430   207]
 [ 1367  1996]]


In [19]:
svc_pred = svc.predict(X_test_scaled)

In [21]:
import pickle 
pickle.dump(svc, open('model.pkl', 'wb'))


In [24]:
out = svc.predict([[1,1,1,1,1,1,1,1,1,1,1,1]])

In [25]:
out

array([1], dtype=int64)